FROM --platform=linux/amd64 docker.io/library/python:3.8-alpine as packages

RUN apk -U add alpine-sdk libxml2-dev libxslt-dev && \
    pip install --upgrade pip && \
    pip wheel -w /packages sanic html5-parser --no-binary=lxml

FROM scratch
COPY --from=packages /packages /packages
