ARG PREFAB_DIST

FROM $PREFAB_DIST as dist
FROM docker:19.03.13-dind

RUN mkdir -p /root/.docker && \
    echo '{"auths":{}}' > /auth.json && \
    ln -fs /auth.json /root/.docker/config.json

COPY --from=dist /container-prefab /usr/local/bin/container-prefab
COPY image/entrypoint.dind /entrypoint-prefab

ENTRYPOINT ["/entrypoint-prefab"]
