name: Release

on:
  release:
    types: [created]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: lexsca
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools setuptools_scm twine wheel

    - name: Build and publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        echo "PREFAB_VERSION=$(python setup.py --version)" >> $GITHUB_ENV
        python setup.py sdist bdist_wheel
        twine upload dist/*

    - name: Build and publish to Docker Hub
      run: |
        pip install dist/*.whl
        prefab --config image/prefab.yaml --repo lexsca/prefab --push-all \
          --target dood:dood-${{ env.PREFAB_VERSION }} dind:dind-${{ env.PREFAB_VERSION }}
