ARG PREFAB_DIST

FROM $PREFAB_DIST as dist
FROM alpine:3.12

RUN mkdir -p /root/.docker && \
    echo '{"auths":{}}' > /auth.json && \
    ln -fs /auth.json /root/.docker/config.json && \
    touch /docker.sock && \
    ln -fs /docker.sock /var/run/docker.sock

COPY --from=dist /prefab /prefab

ENTRYPOINT ["/prefab"]
