ARG PREFAB_DEV

FROM $PREFAB_DEV as dev

WORKDIR /build

COPY lib/ lib/
COPY bin/ bin/
COPY setup.cfg setup.cfg
COPY setup.py setup.py
COPY README.* .

RUN python3 setup.py sdist bdist_wheel && \
    pip3 install dist/*.whl && \
    which prefab | xargs pyinstaller --onefile

FROM scratch

COPY --from=dev /build/dist/* /
