ARG PREFAB_DEV

FROM $PREFAB_DEV as dev
WORKDIR /build

COPY dist/ dist/

RUN pip3 install dist/*.whl && \
    which prefab | xargs pyinstaller --onefile

FROM scratch
COPY --from=dev /build/dist/* /
